"""CN tech sentiment shadow — enums and flag ids (V2.0)."""

from __future__ import annotations

from enum import Enum


class CycleStage(str, Enum):
    S0 = "S0"
    S1 = "S1"
    S2 = "S2"
    S3 = "S3"
    S4 = "S4"
    UNKNOWN = "UNKNOWN"


class ReboundType(str, Enum):
    NONE = "NONE"
    TACTICAL = "TACTICAL"
    CYCLICAL = "CYCLICAL"
    UNKNOWN = "UNKNOWN"


class InterventionMode(str, Enum):
    NONE = "NONE"
    DRAG_NOT_LIFT = "DRAG_NOT_LIFT"
    LIFT_ATTEMPT = "LIFT_ATTEMPT"
    UNKNOWN = "UNKNOWN"


class TransmissionStage(str, Enum):
    HS300_ONLY = "HS300_ONLY"
    TO_CHINEXT = "TO_CHINEXT"
    TO_CSI1000 = "TO_CSI1000"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"


class RescueSequenceStage(str, Enum):
    SELLDOWN = "SELLDOWN"
    PROTECT_INDEX = "PROTECT_INDEX"
    STABILIZE_BROAD = "STABILIZE_BROAD"
    ROTATE_QUALITY = "ROTATE_QUALITY"
    RELEASE_ELASTIC = "RELEASE_ELASTIC"


class BounceQuality(str, Enum):
    NONE = "NONE"
    WEAK_DEAD_CAT = "WEAK_DEAD_CAT"
    INDEX_LED = "INDEX_LED"
    BROAD_CONFIRMED = "BROAD_CONFIRMED"


class StructureQuality(str, Enum):
    POOR = "POOR"
    MIXED = "MIXED"
    GOOD = "GOOD"


class IntradayPath(str, Enum):
    GAP_UP_FADE = "GAP_UP_FADE"
    GAP_DOWN_RECOVERY = "GAP_DOWN_RECOVERY"
    DEEP_V = "DEEP_V"
    LATE_BID_SQUEEZE = "LATE_BID_SQUEEZE"
    TREND = "TREND"
    CHOP = "CHOP"
    UNKNOWN = "UNKNOWN"


class AnchorState(str, Enum):
    ABOVE_BUFFER = "ABOVE_BUFFER"
    IN_ZONE = "IN_ZONE"
    BREAK_TEST = "BREAK_TEST"
    UNKNOWN = "UNKNOWN"


class DataQuality(str, Enum):
    OK = "OK"
    PARTIAL = "PARTIAL"
    DEGRADED = "DEGRADED"
    STALE = "STALE"


class SnapshotSource(str, Enum):
    MOCK = "MOCK"
    MANUAL = "MANUAL"
    LIVE_PARTIAL = "LIVE_PARTIAL"
    LIVE = "LIVE"


# Stable corroboration flags (append-only semantics)
FLAG_CYCLE_PREFIX = "CYCLE_"
FLAG_DRAG_NOT_LIFT = "DRAG_NOT_LIFT"
FLAG_MARGIN_TOP100_STRESS = "MARGIN_TOP100_STRESS"
FLAG_MARGIN_PRESSURE_RELEASE = "MARGIN_PRESSURE_RELEASE"
FLAG_BOARD_STRESS = "BOARD_STRESS"
FLAG_BOARD_RELEASE = "BOARD_RELEASE"
FLAG_MARGIN_LIST_STALE = "MARGIN_LIST_STALE"
FLAG_TRANSMIT_HS300 = "TRANSMIT_HS300"
FLAG_TRANSMIT_CHINEXT = "TRANSMIT_CHINEXT"
FLAG_TRANSMIT_CSI1000 = "TRANSMIT_CSI1000"
FLAG_CSI1000_NEED_LIQUIDITY = "CSI1000_NEED_LIQUIDITY"
FLAG_RIGHT_SIDE_WAIT = "RIGHT_SIDE_WAIT"
FLAG_NO_MAINLINE = "NO_MAINLINE"
FLAG_BOUNCE_NOT_REVERSAL = "BOUNCE_NOT_REVERSAL"
FLAG_WAIT_BROAD_BETA = "WAIT_BROAD_BETA"
FLAG_GAP_UP_FADE = "GAP_UP_FADE"
FLAG_LATE_BROAD_ETF_BID = "LATE_BROAD_ETF_BID"
FLAG_INDEX_BID_TECH_PANIC = "INDEX_BID_TECH_PANIC"
FLAG_CROWDED_UNWIND = "CROWDED_UNWIND"
FLAG_SSE_ANCHOR_TEST = "SSE_ANCHOR_TEST"
FLAG_SSE_ANCHOR_BREAK = "SSE_ANCHOR_BREAK"
FLAG_REBOUND_TACTICAL = "REBOUND_TACTICAL"
FLAG_REBOUND_CYCLICAL_CANDIDATE = "REBOUND_CYCLICAL_CANDIDATE"
FLAG_US_RALLY_FADE = "US_RALLY_FADE"
FLAG_KR_DRAG = "KR_DRAG"
